apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts-cm
data:
  locustfile.py: |
    import time
    from locust import HttpUser, task, events
    from datetime import datetime

    id = ""
    @events.test_start.add_listener
    def on_test_start(**kwargs):
      global id
      now = datetime.now()
      id = now.strftime("%Y%m%d%H%M")

    class HelloWorldUser(HttpUser):
        @task
        def hello_world(self):
            self.client.get("/"+id)
